---
- name: Restart Inference
  become: true
  become_user: "{{ common_service_account.name }}"
  ansible.builtin.systemd:
    name: "{{ inference_server.name }}.service"
    scope: user
    daemon_reload: true
    state: restarted
