---
- name: Install Prerequisite Packages
  ansible.builtin.apt:
    name:
      - libatomic1
      - libquadmath0
    update_cache: true

- name: Add AMD ROCm Repository
  ansible.builtin.deb822_repository:
    name: amdrocm-stable
    types: [deb]
    uris: https://stable.repo.amd.com/rocm/core/packages/ubuntu2604/
    suites: [stable]
    components: [main]
    architectures: [amd64]
    signed_by: https://stable.repo.amd.com/rocm/gpg/packages.gpg

- name: Install AMD ROCm Package
  ansible.builtin.apt:
    name: amdrocm10.0-gfx1151
    update_cache: true

- name: Set TTM Pages Limits
  ansible.builtin.copy:
    dest: /etc/modprobe.d/ttm.conf
    content: |
      options ttm pages_limit={{ rocm_ttm_pages_limit }}
    mode: "0644"
