---
- name: Install ROCm Packages
  ansible.builtin.apt:
    name: rocm
    autoclean: true
    autoremove: true
    update_cache: true
  when: rocm_enabled

- name: Set TTM Pages Limits
  ansible.builtin.copy:
    dest: /etc/modprobe.d/ttm.conf
    content: |
      options ttm pages_limit={{ rocm_ttm_pages_limit }}
    mode: "0644"
  when: rocm_enabled
