---
- name: Deploy LLM Stack
  hosts: all
  become: true

  vars_files:
    - vars/main.yml

  tasks:
    - name: Common Hosts Tasks
      ansible.builtin.import_tasks: tasks/common.yml

    - name: Setup ROCm
      ansible.builtin.import_tasks: tasks/rocm.yml

    - name: Service Account Creation
      ansible.builtin.import_tasks: tasks/service-account.yml

    - name: Setup llama.cpp
      ansible.builtin.import_tasks: tasks/llamacpp.yml

    - name: Setup LiteLLM
      ansible.builtin.import_tasks: tasks/litellm.yml

    - name: Import OpenWebUI
      ansible.builtin.import_tasks: tasks/openwebui.yml
