#!/usr/bin/env bash
set -euo pipefail

read -rp "Target endpoint (default: localhost): " host
host="${host:-localhost}"

if [[ "$host" == "localhost" || "$host" == "127.0.0.1" ]]; then
  ansible_opts=(-i "${host}," --connection=local --ask-become-pass)
else
  ansible_opts=(-i "${host}," --ask-pass --ask-become-pass)
fi

uv run ansible-playbook "${ansible_opts[@]}" setup.yml