---
common_packages:
  - acl
  - podman
  - systemd-container # provides machinectl and journalctl -M
  - tuned
  - ufw

common_tuned_profile: throughput-performance

common_journald_maxuse: 1G

common_service_account:
  name: llm
