---
common_packages:
  - acl
  - podman
  - tuned
  - ufw

common_sysctl:
  net.ipv4.ip_unprivileged_port_start: 80

common_tuned_profile: throughput-performance

common_journald_maxuse: 1G

common_service_account:
  name: llm
