---
- name: Update, Upgrade, and Install Packages
  ansible.builtin.apt:
    name:
      - podman
      - rocm
      - ufw
    autoclean: true
    autoremove: true
    update_cache: true
    upgrade: safe

- name: Configure Firewall Rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "{{ openwebui_port }}"
    - "{{ litellm_port }}"

- name: Configure and Enable Firewall Defaults
  community.general.ufw:
    default: deny
    direction: incoming
    state: enabled

- name: Configure APT Periodic Updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";

- name: Configure Unattended-Upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "origin=*";
      };

      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";

      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-WithUsers "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:00";

- name: Enable Unattended-Upgrades Service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Ensure journald.conf.d Directory
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Limit journald On-Disk Usage
  ansible.builtin.copy:
    dest: /etc/systemd/journald.conf.d/99-size-limits.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      [Journal]
      SystemMaxUse=1G
  notify: Restart journald
