---
- name: Install Host Hardening Packages
  ansible.builtin.apt:
    name:
      - acl
      - ufw
      - unattended-upgrades
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade All Packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    upgrade: safe
  tags:
    - upgrade
    - never

- name: Set ufw Default Deny Incoming
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow Firewall Rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: [22, "{{ openwebui_port }}", "{{ llamacpp_port }}"]

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Configure APT Periodic Updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";

- name: Configure Unattended-Upgrades
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      Unattended-Upgrade::Origins-Pattern {
          "origin=*";
      };

      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";

      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Automatic-Reboot-WithUsers "true";
      Unattended-Upgrade::Automatic-Reboot-Time "03:00";

- name: Enable Unattended-Upgrades Service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started

# TODO FIX
# [ERROR]: Task failed: Module failed: Destination directory /etc/systemd/journald.conf.d does not exist
# Origin: /home/administrator/git/llm/tasks/hardening.yml:73:3

# 71     state: started
# 72
# 73 - name: Cap Journald On-Disk Usage
#      ^ column 3

# fatal: [lisa.home.arpa]: FAILED! => {"changed": false, "checksum": "11d35406216331a232b028fbfd7541c150a7dcf4", "msg": "Destination directory /etc/systemd/journald.conf.d does not exist"}
# - name: Cap Journald On-Disk Usage
#   ansible.builtin.copy:
#     dest: /etc/systemd/journald.conf.d/99-size-limits.conf
#     owner: root
#     group: root
#     mode: "0644"
#     content: |
#       [Journal]
#       SystemMaxUse=1G
#   notify: Restart Journald
