---
- name: Create Service Account
  ansible.builtin.user:
    name: "{{ service_account }}"
    shell: /bin/bash
    groups: render,video
    append: true

- name: Enable Lingering for Service Account
  ansible.builtin.command: loginctl enable-linger {{ service_account }}
  args:
    creates: /var/lib/systemd/linger/{{ service_account }}

- name: Get UID of Service Account
  ansible.builtin.command: id -u {{ username }}
  register: account_uid
  changed_when: false

- name: Create environment.d For {{ username }}
  become_user: "{{ username }}"
  ansible.builtin.file:
    path: /home/{{ username }}/.config/environment.d
    state: directory

- name: Set XDG_RUNTIME_DIR in environment.d File
  become_user: "{{ username }}"
  ansible.builtin.copy:
    dest: /home/{{ username }}/.config/environment.d/10-xdg-runtime.conf
    content: |
      XDG_RUNTIME_DIR=/run/user/{{ account_uid.stdout }}