---
- name: Create Service Account
  ansible.builtin.user:
    name: "{{ service_account.name }}"
    shell: /bin/bash
    groups: render,video
    append: true

- name: Enable Lingering for Service Account
  ansible.builtin.command: loginctl enable-linger {{ service_account.name }}
  args:
    creates: /var/lib/systemd/linger/{{ service_account.name }}

- name: Get UID of Service Account
  ansible.builtin.command: id -u {{ service_account.name }}
  register: account_uid
  changed_when: false

- name: Create environment.d For {{ service_account.name }}
  become: true
  ansible.builtin.file:
    path: /home/{{ service_account.name }}/.config/environment.d
    state: directory
    owner: "{{ service_account.name }}"
    group: "{{ service_account.name }}"
    mode: "0755"

- name: Set XDG_RUNTIME_DIR in environment.d File
  become: true
  ansible.builtin.copy:
    dest: /home/{{ service_account.name }}/.config/environment.d/10-xdg-runtime.conf
    content: |
      XDG_RUNTIME_DIR=/run/user/{{ account_uid.stdout }}
    owner: "{{ service_account.name }}"
    group: "{{ service_account.name }}"
    mode: "0644"
