---
inference_home: "{{ ansible_facts.getent_passwd[common_service_account.name][4] }}"
inference_image: "localhost/llama-server:{{ inference_server.llama_ref }}-rocm{{ inference_server.rocm_version }}"
