---
inference_standalone:
  name: llamacpp-server
  port: 80
  global_settings:
    n-gpu-layers: 999
    threads: 32
  presets:
    - section: unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q8_K_XL
      settings:
        c: 131072
        min-p: 0.00
        spec-draft-n-max: 2
        spec-type: draft-mtp
        temp: 0.6
        top-k: 20
        top-p: 0.95

inference_llamacpp:
  models:
    - name: llamacpp-inference-01
      port: 9000
      environment_variables:
        LLAMA_ARG_ALIAS: qwen-36-thinking
        LLAMA_ARG_CTX_SIZE: 131072
        LLAMA_ARG_HF_REPO: unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q8_K_XL
        LLAMA_ARG_N_GPU_LAYERS: 999
        LLAMA_ARG_SPEC_DRAFT_N_MAX: 2
        LLAMA_ARG_SPEC_TYPE: draft-mtp
        LLAMA_ARG_THREADS: 32
      command: --temp 0.6 --top-p 0.95 --top-k 20 --min-p 0.00
    - name: llamacpp-inference-02
      port: 9001
      environment_variables:
        LLAMA_ARG_ALIAS: qwen-36-instruct
        LLAMA_ARG_CTX_SIZE: 131072
        LLAMA_ARG_HF_REPO: unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q8_K_XL
        LLAMA_ARG_N_GPU_LAYERS: 999
        LLAMA_ARG_SPEC_DRAFT_N_MAX: 2
        LLAMA_ARG_SPEC_TYPE: draft-mtp
        LLAMA_ARG_THREADS: 32
      command: --temp 0.7 --top-p 0.8 --top-k 20 --min-p 0.00 --presence-penalty 1.5 --reasoning off
