---
- name: Create Podman network
  become: true
  become_user: "{{ service_account.name }}"
  containers.podman.podman_network:
    name: artificial-intelligence
    state: present

- name: Create llama.cpp Quadlet Container
  loop: "{{ llamacpp.models }}"
  loop_control:
    loop_var: model
    label: "llamacpp-{{ model.name }}"
  become: true
  become_user: "{{ service_account.name }}"
  containers.podman.podman_container:
    name: "llamacpp-{{ model.name }}"
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    network:
      - artificial-intelligence
    publish:
      - "{{ model.port }}:8080/tcp"
    volume:
      - "llamacpp-{{ model.name }}:/root/.cache/llama.cpp"
    device:
      - /dev/dri
      - /dev/kfd
    group_add:
      - keep-groups
    env: "{{ model.environment_variables | default({}) }}"
    state: quadlet
    command: "{{ model.command }}"

- name: Start llama.cpp Systemd Units
  become: true
  become_user: "{{ service_account.name }}"
  ansible.builtin.systemd:
    name: "llamacpp-{{ model.name }}.service"
    daemon_reload: true
    enabled: true
    scope: user
    state: started
  loop: "{{ llamacpp.models }}"
  loop_control:
    loop_var: model
    label: "{{ model.name }}"
