---
- name: Include Standalone Bare Metal Tasks
  ansible.builtin.include_tasks: standalone-bare-metal.yml
  when: llm_stack_mode == 'standalone-bare-metal'

- name: Include Standalone Podman Tasks
  ansible.builtin.include_tasks: standalone-podman.yml
  when: llm_stack_mode == 'standalone-podman'

- name: Include Modular Tasks
  ansible.builtin.include_tasks: modular.yml
  when: llm_stack_mode == 'modular'
