---
# standalone podman: single llama.cpp server with model presets, in a container
- name: Deploy Quadlet for Standalone llama.cpp Container
  become: true
  become_user: "{{ common_service_account.name }}"
  containers.podman.podman_container:
    name: "{{ inference_standalone.name }}"
    image: ghcr.io/ggml-org/llama.cpp:server-rocm
    network:
      - "{{ podman_setup_network_name }}"
    publish:
      - "{{ inference_standalone.port }}:8080/tcp"
    volume:
      - "{{ inference_standalone.name }}:{{ inference_standalone.cache_path }}"
      - "/home/{{ common_service_account.name }}/.config/llamacpp/models-preset.ini:/models-preset.ini:ro"
    device:
      - /dev/dri
      - /dev/kfd
    env:
      LLAMA_CACHE: "{{ inference_standalone.cache_path }}"
    group_add:
      - keep-groups
    state: quadlet
    command: --models-preset /models-preset.ini --models-max {{ inference_standalone.models_max }}
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Standalone Inference
