---
- name: Create Service Account
  ansible.builtin.user:
    name: "{{ common_service_account.name }}"
    shell: /bin/bash
    groups: "{{ service_account_groups | join(',') }}"
    append: true

- name: Enable Lingering for Service Account
  ansible.builtin.command: loginctl enable-linger {{ common_service_account.name }}
  args:
    creates: /var/lib/systemd/linger/{{ common_service_account.name }}
