---
- name: Create Service Account
  ansible.builtin.user:
    name: "{{ service_account_name }}"
    shell: /bin/bash
    groups: "{{ service_account_groups | join(',') }}"
    append: true

- name: Enable Lingering for Service Account
  ansible.builtin.command: loginctl enable-linger {{ service_account_name }}
  args:
    creates: /var/lib/systemd/linger/{{ service_account_name }}
