---
- name: Configure Base Firewall Rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"
    - "{{ chat_openwebui.port }}"
    - "{{ router_bifrost.port }}"

- name: Configure Inference Container Firewall Rules
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: >-
    {{
      inference_llamacpp.models
      | map(attribute='port')
      | map('string')
      | list
    }}

- name: Configure and Enable Firewall Defaults
  community.general.ufw:
    default: deny
    direction: incoming
    state: enabled
