---
- name: Create Service Account
  ansible.builtin.user:
    name: "{{ service_account.name }}"
    shell: /bin/bash
    groups: render,video
    append: true

- name: Enable Lingering for Service Account
  ansible.builtin.command: loginctl enable-linger {{ service_account.name }}
  args:
    creates: /var/lib/systemd/linger/{{ service_account.name }}
